<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\AiService.DataManager\AiService.DataManager.csproj" />
    <ProjectReference Include="..\AiService.Models\AiService.Domains.csproj" />
  </ItemGroup>

</Project>
